### ISSUE TITLE
should prerequisite of A.02.IR79.layer.metadata.ref link to a set of tests in MD ATS?

### ISSUE THREAD

**Issue by pvgenuchten** [inspire-eu-validation/ats-view-wmts#22]
Now it is defined as a prerequisite that the attached metadata is validated as valid service metadata. 
To fullfill the prerequesite a set of tests in the Metadata Tests will have to be run
Should we include (vice versa) links to tests in other test-suites that will fullfill the prerequisite?

**Comment by aquaglia** [comment]
I do not understand: the attached metadata must be a dataset or series metadata, not service metadata.
If service, an error must be reported.
I also think there can be more than one MetadataURL element inside each layer.

**Comment by ilkkarinne** [comment]
It may be that I had a typo in the text. The prerequisite should only be about the ServiceMetadata (capabilities document) validation, not the referred metadata record.

The version committed as 70db3494184850bfcabeb2c6035aaa1e03de0ebc now also contains a link to the ats-metadata for instructions on checking if the dataset or dataset series metadata record for the underlying data of a layer is a valid INSPIRE metadata record.

**Comment by pvgenuchten** [comment]
Indeed @aquaglia, it was a typo, a layer in wms-capabilities indeed links to one of more dataset-metadata.
