### ISSUE TITLE
Prerequisites should reference other test cases in...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wmts#25]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Prerequisites should reference other test cases in the same ATS or a conformance class, not introduce additional assertions.
# Proposed Change

Move assertions to the test methods.

**Comment by freddy-jrc** [comment]
Harmonze approach with WMS ATS :reuse ATS where it is identical, or modify only what is different.

**Comment by jensscheerlinck** [comment]
This issue will be addressed by the [cross cutting issue 6](https://github.com/inspire-eu-validation/ats-cross-cutting/issues/6)
