### ISSUE TITLE
Link to specific test case is missing for prerequi...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wmts#26]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Link to specific test case is missing for prerequisites
# Proposed Change

Update prerequisites with specific reference tests

**Comment by freddy-jrc** [comment]
Harmonze approach with WMS ATS :reuse ATS where it is identical, or modify only what is different.

**Comment by jensscheerlinck** [comment]
This will be addressed by [cross cutting issue 9](https://github.com/inspire-eu-validation/ats-cross-cutting/issues/9)
