### ISSUE TITLE
IR 89

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wmts#37]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Add a test covering the ETRS based CRS in the same way as in WMS. Consider to add here the CRS here as well.
# Proposed Change

Add an additional test or reference the test from WMS ATS.

**Comment by cportele** [comment]
Agreed. Requirement 89 is classified as not testable, but this is different in WMS where the requirement is similar.

Proposed resolution:
- Add a new test case for req 89 that follows the same approach as in WMS.

**Comment by cportele** [comment]
Note after April 15 call: See also https://github.com/inspire-eu-validation/ats-view-wms/issues/114

**Comment by cportele** [comment]
Resolution: Ensure consistency between CRS tests for WMS and WMTS.
