### ISSUE TITLE
IR74-IR75, IR78, IR81, IR82

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wmts#38]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

The requirements related to conformance with the WMTS standard are not represented in the ATS. 
# Proposed Change

The ATS should reference the OGC WMTS conformance class(es) that are a dependency (but not reference individual WMTS tests). With a view to ETSs for those, in general, the tests for WMTS 1.0.0 should be provided by OGC CITE.

**Comment by freddy-jrc** [comment]
Harmonze approach with WMS ATS :reuse ATS where it is identical, or modify only what is different.

Also the schema validation requirement as in [A.03.IR05.schema.validation](https://github.com/inspire-eu-validation/ats-view-wms/blob/master/A.03.IR05.schema.validation.md) (for WMS)  seems to be missing.
