### ISSUE TITLE
Tile Matrix

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/ats-view-wmts#39]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Consider to add a requirement for a tile matrix system, since a commonly used tile matrix is crucial for interoperable cross-border WMTS.  
# Proposed Change

Add a commonly used tile System (e.g. Pseudo-Wercator or InspireCRS84Quad) as requirement and a corresponding test case.

**Comment by cportele** [comment]
I agree in principle, but this requires a change in the Technical Guidance by the MIG first.

Proposed resolution:
- Refer the issue to the MIG.

**Comment by cportele** [comment]
Proposed resolution accepted by default. See [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10#Next-steps).
